void main() {
    exception BadException;

    try {
        protest("Wah!");
    } catch BadException() {
        print("Hi");
    }
}
